# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-19 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_speakers', '0002_speaker_twitter_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='github_account',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Github Account'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='phone_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Phone Number'),
        ),
    ]
